# Generated by Django 4.2.19 on 2025-02-13 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0002_booking'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotel',
            name='city',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
